class_name Brawl
extends RefCounted
## A physical disagreement with a patient.
##
## Asked for by name: "maybe I can fight my patients — if I win, they're staying
## in the hospital longer; if they win, I lose medical bills plus the medical
## day is ended plus no crime at night that night."
##
## Which is a better mechanic than it sounds, because it is the only thing in
## the game where the DOWNSIDE is your own time rather than your reputation. Everything
## else you do badly costs you standing you can still trade against; losing a
## fight to a man with a sore elbow costs you the afternoon, the evening and a
## bill, and no amount of paperwork makes that back.
##
## Nothing here is a treatment and none of it goes on a chart as one. Winning
## leaves them with an injury they did not arrive with, in a room with a door,
## and the ward's existing machinery for "who saw that" does the rest.

## Hits. This is meant to be hard.
##
## "Fights should be legit difficult — they have such big payoffs and are too
## easy for them right now." Fair: three days of bed-rate for a patient who
## cannot remember it happened is one of the best-paying things in the game, and
## it was six coin flips with a second of warning each.
##
## Eight to put them down, three to put you down, a wind-up that starts short
## and gets shorter, a window a fifth of a second wide — and FEINTS, which are
## the thing that makes it a read rather than a reaction. What they cost you is
## not milliseconds; it is that the first commitment is a lie often enough that
## you cannot trust it.
const THEIR_GUARD := 8
const YOUR_GUARD := 3

## How long the wind-up lasts, and it does not last long.
const TELEGRAPH_START := 0.72
const TELEGRAPH_MIN := 0.26
const TELEGRAPH_STEP := 0.052

## How far either side of the strike a block still counts, in seconds.
const WINDOW := 0.17

## Seconds after a swing lands before the next one starts.
const RECOVER := 0.42

## The chance a wind-up is a lie, and how far through it they switch hands. It
## climbs with the exchange, so the fight gets harder in the way a fight does:
## they work out that you are reading them.
const FEINT_AT := 0.55
const FEINT_START := 0.10
const FEINT_STEP := 0.055
const FEINT_MAX := 0.55

static func feint_chance(exchange: int) -> float:
	return minf(FEINT_MAX, FEINT_START + FEINT_STEP * float(exchange))

static func telegraph_for(exchange: int) -> float:
	return maxf(TELEGRAPH_MIN, TELEGRAPH_START - TELEGRAPH_STEP * float(exchange))

## Who will actually square up.
##
## Anybody admitted, awake and not already discharged. It is not gated on them
## being angry — the joke is that you can start it — but somebody who already
## has a reason is more likely to swing first, which the screen uses for its
## opening line rather than for any rule.
##
## And once a day each, because the last clause is the whole economy of the
## thing. Winning knocks them out, and out cold is an attention of zero at the
## instant the altercation goes out — so the only person in the room is
## guaranteed not to witness it. Pressing E on a slumped body still opens their
## card (`wake_up` refuses to bring them round, but nothing stops the card), and
## `stand_and_square_up` will haul an unconscious patient back onto their feet,
## so without this you could stand over one man and collect three days of
## bed-rate and a fresh contusion as many times as you had the patience for,
## with no evidence generated by any of it. Every procedure is already once per
## patient per day (`Patient.seen_to_today`); the best-paying verb in the game
## does not get to be the exception.
##
## Kept on the patient rather than on the body, because the body is a node with
## a lifetime of its own and this has to be readable from a menu. `knock_out()`
## stamps the same meta that `PatientNPC._on_shift_started` reads to bring them
## round, so the day turning over is the one thing that opens them up again.
static func can_fight(p) -> bool:
	if p == null or p.discharged:
		return false
	if not p.admitted:
		return false
	return int(p.out_cold_day) != GameState.day

## Is there still a shift going on to have a fight during?
##
## `can_fight()` is a statement about the PERSON — admitted, still here, not
## already on the floor today — and is deliberately clock-free so the data layer
## has no opinion about phases. This is the other half, and both the button and
## BrawlSystem.start() read it, because they were disagreeing: the card went on
## offering "Square up" after the day was signed off (reachable from "Go and fix
## it" on the chart review), the fight refused to start, and the player got a
## button that did nothing with no explanation.
static func on_the_clock() -> bool:
	return GameState.phase != GameState.Phase.CHART_REVIEW \
		and GameState.phase != GameState.Phase.POST_SHIFT \
		and GameState.phase != GameState.Phase.GAME_OVER

## Do they have a grievance? Only changes what gets said.
static func has_a_grievance(p, mind) -> bool:
	if p == null:
		return false
	if not p.acquired_injuries().is_empty():
		return true
	if p.is_overdue():
		return true
	if mind != null and mind.strongest(GameState.career_minutes) != null:
		return true
	return false

const OPENERS := {
	"grievance": [
		"You've got a nerve showing up in here.",
		"I've been thinking about this all week.",
		"No. No, we're doing this now.",
	],
	"ordinary": [
		"Sorry — is this about the parking?",
		"I don't want any trouble. I'm just going to have some anyway.",
		"Right. Well. If you insist.",
	],
}

static func opener(p, mind, seed_n: int) -> String:
	var pool: Array = OPENERS["grievance" if has_a_grievance(p, mind) else "ordinary"]
	return String(pool[absi(seed_n) % pool.size()])

## What happens afterwards, as data. The screen grades a brawl and hands the
## spec over; `apply()` is the only thing that touches the world.
const OUTCOMES := {
	"won": {
		"label": "They sit back down",
		"stay": 3.0, "harm": "disputed_contusion", "visual": 0.85, "sue": 0.30,
		"line": "They are staying in. For observation. Of the bruising.",
		"say": ["Alright. ALRIGHT.", "I'd like to make a complaint.",
			"That is going in a letter."],
	},
	"lost": {
		"label": "You wake up on the floor",
		"bill": 1800, "visual": 0.95, "sue": 0.0,
		"line": "The rest of the day is gone, the evening with it, and the "
			+ "hospital has billed you for the stitches.",
		"say": ["Somebody get a doctor. Not him. A different one.",
			"He went down like a filing cabinet.", "Is he meant to be that colour?"],
	},
}

static func outcome(won: bool) -> Dictionary:
	return (OUTCOMES["won"] if won else OUTCOMES["lost"]).duplicate(true)

## The bill for losing, which is the only number in this that scales — a broken
## nose costs the same on day one and day thirty, and on day thirty that is
## nothing at all.
static func bill_for(day: int) -> int:
	return int(OUTCOMES["lost"]["bill"]) + 260 * maxi(0, day - 1)
